#ifndef SYNC_ANALYSIS_INTEGRATION_SHARED_EVENTS_H_
#define SYNC_ANALYSIS_INTEGRATION_SHARED_EVENTS_H_

#include <sync_analysis.h>

#ifdef __cplusplus
extern "C" {
#endif

enum {
  SA_EV_THREAD = 1u << 0,
  SA_EV_MUTEX = 1u << 1,
  SA_EV_REC_MUTEX = 1u << 2,
  SA_EV_RWLOCK = 1u << 3,

  SA_EV_CREATE = 1u << 4,
  SA_EV_TRY_WR_LOCK = 1u << 5,
  SA_EV_BEFORE_WR_LOCK = 1u << 6,
  SA_EV_AFTER_WR_LOCK = 1u << 7,
  SA_EV_WR_UNLOCK = 1u << 8,
  SA_EV_TRY_RD_LOCK = 1u << 9,
  SA_EV_BEFORE_RD_LOCK = 1u << 10,
  SA_EV_AFTER_RD_LOCK = 1u << 11,
  SA_EV_RD_UNLOCK = 1u << 12,
  SA_EV_DESTROY = 1u << 13,
  SA_EV_JOIN = 1u << 14,
  SA_EV_DETACH = 1u << 15,
};

enum {
  SA_EV_THREAD_ON_CREATE = SA_EV_THREAD | SA_EV_CREATE,
  SA_EV_THREAD_ON_JOIN = SA_EV_THREAD | SA_EV_JOIN,
  SA_EV_THREAD_ON_DETACH = SA_EV_THREAD | SA_EV_DETACH,

  SA_EV_MUTEX_ON_CREATE = SA_EV_MUTEX | SA_EV_CREATE,
  SA_EV_MUTEX_ON_TRY_LOCK = SA_EV_MUTEX | SA_EV_TRY_WR_LOCK,
  SA_EV_MUTEX_BEFORE_LOCK = SA_EV_MUTEX | SA_EV_BEFORE_WR_LOCK,
  SA_EV_MUTEX_AFTER_LOCK = SA_EV_MUTEX | SA_EV_AFTER_WR_LOCK,
  SA_EV_MUTEX_ON_UNLOCK = SA_EV_MUTEX | SA_EV_WR_UNLOCK,
  SA_EV_MUTEX_ON_DESTROY = SA_EV_MUTEX | SA_EV_DESTROY,

  SA_EV_REC_MUTEX_ON_CREATE = SA_EV_REC_MUTEX | SA_EV_CREATE,
  SA_EV_REC_MUTEX_ON_TRY_LOCK = SA_EV_REC_MUTEX | SA_EV_TRY_WR_LOCK,
  SA_EV_REC_MUTEX_BEFORE_LOCK = SA_EV_REC_MUTEX | SA_EV_BEFORE_WR_LOCK,
  SA_EV_REC_MUTEX_AFTER_LOCK = SA_EV_REC_MUTEX | SA_EV_AFTER_WR_LOCK,
  SA_EV_REC_MUTEX_ON_UNLOCK = SA_EV_REC_MUTEX | SA_EV_WR_UNLOCK,
  SA_EV_REC_MUTEX_ON_DESTROY = SA_EV_REC_MUTEX | SA_EV_DESTROY,

  SA_EV_RWLOCK_ON_CREATE = SA_EV_RWLOCK | SA_EV_CREATE,
  SA_EV_RWLOCK_ON_TRY_RD_LOCK = SA_EV_RWLOCK | SA_EV_TRY_RD_LOCK,
  SA_EV_RWLOCK_BEFORE_RD_LOCK = SA_EV_RWLOCK | SA_EV_BEFORE_RD_LOCK,
  SA_EV_RWLOCK_AFTER_RD_LOCK = SA_EV_RWLOCK | SA_EV_AFTER_RD_LOCK,
  SA_EV_RWLOCK_ON_RD_UNLOCK = SA_EV_RWLOCK | SA_EV_RD_UNLOCK,
  SA_EV_RWLOCK_ON_TRY_WR_LOCK = SA_EV_RWLOCK | SA_EV_TRY_WR_LOCK,
  SA_EV_RWLOCK_BEFORE_WR_LOCK = SA_EV_RWLOCK | SA_EV_BEFORE_WR_LOCK,
  SA_EV_RWLOCK_AFTER_WR_LOCK = SA_EV_RWLOCK | SA_EV_AFTER_WR_LOCK,
  SA_EV_RWLOCK_ON_WR_UNLOCK = SA_EV_RWLOCK | SA_EV_WR_UNLOCK,
  SA_EV_RWLOCK_ON_DESTROY = SA_EV_RWLOCK | SA_EV_DESTROY,
};

#ifdef __cplusplus
}
#endif

#endif
