#ifndef SYNC_ANALYSIS_LIB_SRC_EVENT_TYPE_H_
#define SYNC_ANALYSIS_LIB_SRC_EVENT_TYPE_H_

typedef enum {
  SA_EV_MUTEX_ON_CREATE,
  SA_EV_MUTEX_ON_TRY_LOCK,
  SA_EV_MUTEX_BEFORE_LOCK,
  SA_EV_MUTEX_AFTER_LOCK,
  SA_EV_MUTEX_ON_UNLOCK,
  SA_EV_MUTEX_ON_DESTROY,
  SA_EV_RWLOCK_ON_CREATE,
  SA_EV_RWLOCK_ON_TRY_LOCK,
  SA_EV_RWLOCK_BEFORE_LOCK,
  SA_EV_RWLOCK_AFTER_LOCK,
  SA_EV_RWLOCK_ON_UNLOCK,
  SA_EV_RWLOCK_ON_W_TRY_LOCK,
  SA_EV_RWLOCK_BEFORE_W_LOCK,
  SA_EV_RWLOCK_AFTER_W_LOCK,
  SA_EV_RWLOCK_ON_W_UNLOCK,
  SA_EV_RWLOCK_ON_DESTROY,
} EventType;

#endif
