#ifndef SYNC_ANALYSIS_LIB_SRC_EVENT_TYPE_H_
#define SYNC_ANALYSIS_LIB_SRC_EVENT_TYPE_H_

typedef enum {
  SA_EV_THREAD_ON_CREATE,
  SA_EV_THREAD_ON_JOIN,
  SA_EV_THREAD_ON_DETACH,
  SA_EV_MUTEX_ON_CREATE,
  SA_EV_MUTEX_ON_TRY_LOCK,
  SA_EV_MUTEX_BEFORE_LOCK,
  SA_EV_MUTEX_AFTER_LOCK,
  SA_EV_MUTEX_ON_UNLOCK,
  SA_EV_MUTEX_ON_DESTROY,
  SA_EV_REC_MUTEX_ON_CREATE,
  SA_EV_REC_MUTEX_ON_TRY_LOCK,
  SA_EV_REC_MUTEX_BEFORE_LOCK,
  SA_EV_REC_MUTEX_AFTER_LOCK,
  SA_EV_REC_MUTEX_ON_UNLOCK,
  SA_EV_REC_MUTEX_ON_DESTROY,
  SA_EV_RWLOCK_ON_CREATE,
  SA_EV_RWLOCK_ON_TRY_RD_LOCK,
  SA_EV_RWLOCK_BEFORE_RD_LOCK,
  SA_EV_RWLOCK_AFTER_RD_LOCK,
  SA_EV_RWLOCK_ON_RD_UNLOCK,
  SA_EV_RWLOCK_ON_TRY_WR_LOCK,
  SA_EV_RWLOCK_BEFORE_WR_LOCK,
  SA_EV_RWLOCK_AFTER_WR_LOCK,
  SA_EV_RWLOCK_ON_WR_UNLOCK,
  SA_EV_RWLOCK_ON_DESTROY,
} EventType;

#endif
