#ifndef SYNC_ANALYSIS_LIB_SRC_EVENT_TYPE_H_
#define SYNC_ANALYSIS_LIB_SRC_EVENT_TYPE_H_

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  SA_EV_THREAD_ON_CREATE = 0,
  SA_EV_THREAD_ON_JOIN = 1,
  SA_EV_THREAD_ON_DETACH = 2,
  SA_EV_MUTEX_ON_CREATE = 3,
  SA_EV_MUTEX_ON_TRY_LOCK = 4,
  SA_EV_MUTEX_BEFORE_LOCK = 5,
  SA_EV_MUTEX_AFTER_LOCK = 6,
  SA_EV_MUTEX_ON_UNLOCK = 7,
  SA_EV_MUTEX_ON_DESTROY = 8,
  SA_EV_REC_MUTEX_ON_CREATE = 9,
  SA_EV_REC_MUTEX_ON_TRY_LOCK = 10,
  SA_EV_REC_MUTEX_BEFORE_LOCK = 11,
  SA_EV_REC_MUTEX_AFTER_LOCK = 12,
  SA_EV_REC_MUTEX_ON_UNLOCK = 13,
  SA_EV_REC_MUTEX_ON_DESTROY = 14,
  SA_EV_RWLOCK_ON_CREATE = 15,
  SA_EV_RWLOCK_ON_TRY_RD_LOCK = 16,
  SA_EV_RWLOCK_BEFORE_RD_LOCK = 17,
  SA_EV_RWLOCK_AFTER_RD_LOCK = 18,
  SA_EV_RWLOCK_ON_RD_UNLOCK = 19,
  SA_EV_RWLOCK_ON_TRY_WR_LOCK = 20,
  SA_EV_RWLOCK_BEFORE_WR_LOCK = 21,
  SA_EV_RWLOCK_AFTER_WR_LOCK = 22,
  SA_EV_RWLOCK_ON_WR_UNLOCK = 23,
  SA_EV_RWLOCK_ON_DESTROY = 24,
} EventType;

#ifdef __cplusplus
}
#endif

#endif
